apiVersion: v1
kind: Service
metadata:
  labels:
    app: thesecondapp
  name: thesecondapp-service
  namespace: default
spec:
  selector:
    app: thesecondapp
  ports:
    - name: thesecondapp-service
      protocol: TCP
      port: 3000
      targetPort: 3000