apiVersion: v1
kind: Service
metadata:
  labels:
    app: thefirstapp
  name: thefirstapp-service
  namespace: default
spec:
  selector:
    app: thefirstapp
  ports:
    - name: thefirstapp-service
      protocol: TCP
      port: 3000
      targetPort: 3000